name: Run game

on:
  push:
    branches:
      - main

jobs:
  run-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "no requirements"

      - name: Run game
        run: python game.py | tee game_output.log

      - name: Upload game log
        uses: actions/upload-artifact@v4
        with:
          name: game-log
          path: game_output.log
